server:
  port: 8080

spring:
  datasource:
    username: root
    password: 3843831
    url: jdbc:mysql://localhost:3306/test
  jackson:
    default-property-inclusion: non_null

mybatis:
  configuration:
    map-underscore-to-camel-case: true
